"""add cascade delete to messages

Revision ID: 0ab8ee0a782c
Revises: 0160b0f70a02
Create Date: 2025-07-12 11:25:03.863631

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0ab8ee0a782c"
down_revision: Union[str, None] = "0160b0f70a02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
