"""add passive_delete_v2

Revision ID: 1d0f26dbbef5
Revises: afdaf9aa539c
Create Date: 2025-09-17 22:48:31.379106

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1d0f26dbbef5"
down_revision: Union[str, None] = "afdaf9aa539c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
