"""add investigation roles permissions


Revision ID: 6be831edfda7
Revises: c82bf6af92e5
Create Date: 2025-09-17 22:02:46.159090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6be831edfda7"
down_revision: Union[str, None] = "c82bf6af92e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investigation_user_roles",
        sa.Column(
            "roles",
            postgresql.ARRAY(
                sa.Enum(
                    "OWNER",
                    "EDITOR",
                    "VIEWER",
                    name="role_enum",
                    create_constraint=True,
                )
            ),
            server_default="{}",
            nullable=False,
        ),
    )
    op.drop_column("investigation_user_roles", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investigation_user_roles",
        sa.Column(
            "role",
            postgresql.ENUM("OWNER", "EDITOR", "VIEWER", name="role_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("investigation_user_roles", "roles")
    # ### end Alembic commands ###
