"""Add relationship between investigations and sketches

Revision ID: 76f5436251e3
Revises: d0a8e5b5a7b9
Create Date: 2025-05-19 23:59:33.721812

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "76f5436251e3"
down_revision: Union[str, None] = "d0a8e5b5a7b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
