"""add chat and chat message

Revision ID: 8ac522441108
Revises: e403a4152f6b
Create Date: 2025-07-11 16:27:23.975758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ac522441108"
down_revision: Union[str, None] = "e403a4152f6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("investigation_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["profiles.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chats_investigation_id", "chats", ["investigation_id"], unique=False
    )
    op.create_index("idx_chats_owner_id", "chats", ["owner_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_chat_id", "messages", ["chat_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_messages_chat_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_chats_owner_id", table_name="chats")
    op.drop_index("idx_chats_investigation_id", table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
