"""fix_backpopulate issue

Revision ID: 8d0e12b68d1e
Revises: 1d0f26dbbef5
Create Date: 2025-09-17 22:55:20.721587

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8d0e12b68d1e"
down_revision: Union[str, None] = "1d0f26dbbef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
