"""add passive_delete

Revision ID: afdaf9aa539c
Revises: 6be831edfda7
Create Date: 2025-09-17 22:46:21.139127

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "afdaf9aa539c"
down_revision: Union[str, None] = "6be831edfda7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
