"""Add relationship between investigations and sketches

Revision ID: d0a8e5b5a7b9
Revises: 40ece72583b7
Create Date: 2025-05-19 23:57:29.084171

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d0a8e5b5a7b9"
down_revision: Union[str, None] = "40ece72583b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
