"""init

Revision ID: d39941278a91
Revises: 6e49acfb3816
Create Date: 2025-09-17 21:52:57.142634

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d39941278a91"
down_revision: Union[str, None] = "6e49acfb3816"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
