"""add_category_to_custom_types

Revision ID: f4d42260273d
Revises: a1f2b3c4d5e6
Create Date: 2026-06-06 14:47:31.692222

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4d42260273d"
down_revision: Union[str, None] = "a1f2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "custom_types",
        sa.Column(
            "category",
            sa.String(),
            server_default="custom_types_category",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("custom_types", "category")
    # ### end Alembic commands ###
