/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MiddlewareRouteImport } from './routes/middleware'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth.dashboard.index'
import { Route as AuthDashboardVaultRouteImport } from './routes/_auth.dashboard.vault'
import { Route as AuthDashboardToolsRouteImport } from './routes/_auth.dashboard.tools'
import { Route as AuthDashboardProfileRouteImport } from './routes/_auth.dashboard.profile'
import { Route as AuthDashboardFlowsIndexRouteImport } from './routes/_auth.dashboard.flows.index'
import { Route as AuthDashboardEnrichersIndexRouteImport } from './routes/_auth.dashboard.enrichers.index'
import { Route as AuthDashboardCustomTypesIndexRouteImport } from './routes/_auth.dashboard.custom-types.index'
import { Route as AuthDashboardInvestigationsInvestigationIdRouteImport } from './routes/_auth.dashboard.investigations.$investigationId'
import { Route as AuthDashboardFlowsFlowIdRouteImport } from './routes/_auth.dashboard.flows.$flowId'
import { Route as AuthDashboardEnrichersNewRouteImport } from './routes/_auth.dashboard.enrichers.new'
import { Route as AuthDashboardEnrichersEnricherIdRouteImport } from './routes/_auth.dashboard.enrichers.$enricherId'
import { Route as AuthDashboardCustomTypesTypeIdRouteImport } from './routes/_auth.dashboard.custom-types.$typeId'
import { Route as AuthDashboardInvestigationsInvestigationIdIndexRouteImport } from './routes/_auth.dashboard.investigations.$investigationId.index'
import { Route as AuthDashboardInvestigationsInvestigationIdTypeIdRouteImport } from './routes/_auth.dashboard.investigations.$investigationId.$type.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport
} as any)
const MiddlewareRoute = MiddlewareRouteImport.update({
  id: '/middleware',
  path: '/middleware',
  getParentRoute: () => rootRouteImport
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardVaultRoute = AuthDashboardVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardToolsRoute = AuthDashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardProfileRoute = AuthDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardFlowsIndexRoute = AuthDashboardFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardEnrichersIndexRoute = AuthDashboardEnrichersIndexRouteImport.update({
  id: '/enrichers/',
  path: '/enrichers/',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardCustomTypesIndexRoute = AuthDashboardCustomTypesIndexRouteImport.update({
  id: '/custom-types/',
  path: '/custom-types/',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardInvestigationsInvestigationIdRoute =
  AuthDashboardInvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => AuthDashboardRoute
  } as any)
const AuthDashboardFlowsFlowIdRoute = AuthDashboardFlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardEnrichersNewRoute = AuthDashboardEnrichersNewRouteImport.update({
  id: '/enrichers/new',
  path: '/enrichers/new',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardEnrichersEnricherIdRoute = AuthDashboardEnrichersEnricherIdRouteImport.update({
  id: '/enrichers/$enricherId',
  path: '/enrichers/$enricherId',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardCustomTypesTypeIdRoute = AuthDashboardCustomTypesTypeIdRouteImport.update({
  id: '/custom-types/$typeId',
  path: '/custom-types/$typeId',
  getParentRoute: () => AuthDashboardRoute
} as any)
const AuthDashboardInvestigationsInvestigationIdIndexRoute =
  AuthDashboardInvestigationsInvestigationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthDashboardInvestigationsInvestigationIdRoute
  } as any)
const AuthDashboardInvestigationsInvestigationIdTypeIdRoute =
  AuthDashboardInvestigationsInvestigationIdTypeIdRouteImport.update({
    id: '/$type/$id',
    path: '/$type/$id',
    getParentRoute: () => AuthDashboardInvestigationsInvestigationIdRoute
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/middleware': typeof MiddlewareRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthDashboardRouteWithChildren
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard/tools': typeof AuthDashboardToolsRoute
  '/dashboard/vault': typeof AuthDashboardVaultRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/custom-types/$typeId': typeof AuthDashboardCustomTypesTypeIdRoute
  '/dashboard/enrichers/$enricherId': typeof AuthDashboardEnrichersEnricherIdRoute
  '/dashboard/enrichers/new': typeof AuthDashboardEnrichersNewRoute
  '/dashboard/flows/$flowId': typeof AuthDashboardFlowsFlowIdRoute
  '/dashboard/investigations/$investigationId': typeof AuthDashboardInvestigationsInvestigationIdRouteWithChildren
  '/dashboard/custom-types': typeof AuthDashboardCustomTypesIndexRoute
  '/dashboard/enrichers': typeof AuthDashboardEnrichersIndexRoute
  '/dashboard/flows': typeof AuthDashboardFlowsIndexRoute
  '/dashboard/investigations/$investigationId/': typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  '/dashboard/investigations/$investigationId/$type/$id': typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/middleware': typeof MiddlewareRoute
  '/register': typeof RegisterRoute
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard/tools': typeof AuthDashboardToolsRoute
  '/dashboard/vault': typeof AuthDashboardVaultRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/custom-types/$typeId': typeof AuthDashboardCustomTypesTypeIdRoute
  '/dashboard/enrichers/$enricherId': typeof AuthDashboardEnrichersEnricherIdRoute
  '/dashboard/enrichers/new': typeof AuthDashboardEnrichersNewRoute
  '/dashboard/flows/$flowId': typeof AuthDashboardFlowsFlowIdRoute
  '/dashboard/custom-types': typeof AuthDashboardCustomTypesIndexRoute
  '/dashboard/enrichers': typeof AuthDashboardEnrichersIndexRoute
  '/dashboard/flows': typeof AuthDashboardFlowsIndexRoute
  '/dashboard/investigations/$investigationId': typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  '/dashboard/investigations/$investigationId/$type/$id': typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/middleware': typeof MiddlewareRoute
  '/register': typeof RegisterRoute
  '/_auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/_auth/dashboard/profile': typeof AuthDashboardProfileRoute
  '/_auth/dashboard/tools': typeof AuthDashboardToolsRoute
  '/_auth/dashboard/vault': typeof AuthDashboardVaultRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/custom-types/$typeId': typeof AuthDashboardCustomTypesTypeIdRoute
  '/_auth/dashboard/enrichers/$enricherId': typeof AuthDashboardEnrichersEnricherIdRoute
  '/_auth/dashboard/enrichers/new': typeof AuthDashboardEnrichersNewRoute
  '/_auth/dashboard/flows/$flowId': typeof AuthDashboardFlowsFlowIdRoute
  '/_auth/dashboard/investigations/$investigationId': typeof AuthDashboardInvestigationsInvestigationIdRouteWithChildren
  '/_auth/dashboard/custom-types/': typeof AuthDashboardCustomTypesIndexRoute
  '/_auth/dashboard/enrichers/': typeof AuthDashboardEnrichersIndexRoute
  '/_auth/dashboard/flows/': typeof AuthDashboardFlowsIndexRoute
  '/_auth/dashboard/investigations/$investigationId/': typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  '/_auth/dashboard/investigations/$investigationId/$type/$id': typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/middleware'
    | '/register'
    | '/dashboard'
    | '/dashboard/profile'
    | '/dashboard/tools'
    | '/dashboard/vault'
    | '/dashboard/'
    | '/dashboard/custom-types/$typeId'
    | '/dashboard/enrichers/$enricherId'
    | '/dashboard/enrichers/new'
    | '/dashboard/flows/$flowId'
    | '/dashboard/investigations/$investigationId'
    | '/dashboard/custom-types'
    | '/dashboard/enrichers'
    | '/dashboard/flows'
    | '/dashboard/investigations/$investigationId/'
    | '/dashboard/investigations/$investigationId/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/middleware'
    | '/register'
    | '/dashboard/profile'
    | '/dashboard/tools'
    | '/dashboard/vault'
    | '/dashboard'
    | '/dashboard/custom-types/$typeId'
    | '/dashboard/enrichers/$enricherId'
    | '/dashboard/enrichers/new'
    | '/dashboard/flows/$flowId'
    | '/dashboard/custom-types'
    | '/dashboard/enrichers'
    | '/dashboard/flows'
    | '/dashboard/investigations/$investigationId'
    | '/dashboard/investigations/$investigationId/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/middleware'
    | '/register'
    | '/_auth/dashboard'
    | '/_auth/dashboard/profile'
    | '/_auth/dashboard/tools'
    | '/_auth/dashboard/vault'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/custom-types/$typeId'
    | '/_auth/dashboard/enrichers/$enricherId'
    | '/_auth/dashboard/enrichers/new'
    | '/_auth/dashboard/flows/$flowId'
    | '/_auth/dashboard/investigations/$investigationId'
    | '/_auth/dashboard/custom-types/'
    | '/_auth/dashboard/enrichers/'
    | '/_auth/dashboard/flows/'
    | '/_auth/dashboard/investigations/$investigationId/'
    | '/_auth/dashboard/investigations/$investigationId/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  MiddlewareRoute: typeof MiddlewareRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware': {
      id: '/middleware'
      path: '/middleware'
      fullPath: '/middleware'
      preLoaderRoute: typeof MiddlewareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/vault': {
      id: '/_auth/dashboard/vault'
      path: '/vault'
      fullPath: '/dashboard/vault'
      preLoaderRoute: typeof AuthDashboardVaultRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/tools': {
      id: '/_auth/dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof AuthDashboardToolsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/profile': {
      id: '/_auth/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthDashboardProfileRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/flows/': {
      id: '/_auth/dashboard/flows/'
      path: '/flows'
      fullPath: '/dashboard/flows'
      preLoaderRoute: typeof AuthDashboardFlowsIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/enrichers/': {
      id: '/_auth/dashboard/enrichers/'
      path: '/enrichers'
      fullPath: '/dashboard/enrichers'
      preLoaderRoute: typeof AuthDashboardEnrichersIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/custom-types/': {
      id: '/_auth/dashboard/custom-types/'
      path: '/custom-types'
      fullPath: '/dashboard/custom-types'
      preLoaderRoute: typeof AuthDashboardCustomTypesIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/investigations/$investigationId': {
      id: '/_auth/dashboard/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/dashboard/investigations/$investigationId'
      preLoaderRoute: typeof AuthDashboardInvestigationsInvestigationIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/flows/$flowId': {
      id: '/_auth/dashboard/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/dashboard/flows/$flowId'
      preLoaderRoute: typeof AuthDashboardFlowsFlowIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/enrichers/new': {
      id: '/_auth/dashboard/enrichers/new'
      path: '/enrichers/new'
      fullPath: '/dashboard/enrichers/new'
      preLoaderRoute: typeof AuthDashboardEnrichersNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/enrichers/$enricherId': {
      id: '/_auth/dashboard/enrichers/$enricherId'
      path: '/enrichers/$enricherId'
      fullPath: '/dashboard/enrichers/$enricherId'
      preLoaderRoute: typeof AuthDashboardEnrichersEnricherIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/custom-types/$typeId': {
      id: '/_auth/dashboard/custom-types/$typeId'
      path: '/custom-types/$typeId'
      fullPath: '/dashboard/custom-types/$typeId'
      preLoaderRoute: typeof AuthDashboardCustomTypesTypeIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/_auth/dashboard/investigations/$investigationId/': {
      id: '/_auth/dashboard/investigations/$investigationId/'
      path: '/'
      fullPath: '/dashboard/investigations/$investigationId/'
      preLoaderRoute: typeof AuthDashboardInvestigationsInvestigationIdIndexRouteImport
      parentRoute: typeof AuthDashboardInvestigationsInvestigationIdRoute
    }
    '/_auth/dashboard/investigations/$investigationId/$type/$id': {
      id: '/_auth/dashboard/investigations/$investigationId/$type/$id'
      path: '/$type/$id'
      fullPath: '/dashboard/investigations/$investigationId/$type/$id'
      preLoaderRoute: typeof AuthDashboardInvestigationsInvestigationIdTypeIdRouteImport
      parentRoute: typeof AuthDashboardInvestigationsInvestigationIdRoute
    }
  }
}

interface AuthDashboardInvestigationsInvestigationIdRouteChildren {
  AuthDashboardInvestigationsInvestigationIdIndexRoute: typeof AuthDashboardInvestigationsInvestigationIdIndexRoute
  AuthDashboardInvestigationsInvestigationIdTypeIdRoute: typeof AuthDashboardInvestigationsInvestigationIdTypeIdRoute
}

const AuthDashboardInvestigationsInvestigationIdRouteChildren: AuthDashboardInvestigationsInvestigationIdRouteChildren =
  {
    AuthDashboardInvestigationsInvestigationIdIndexRoute:
      AuthDashboardInvestigationsInvestigationIdIndexRoute,
    AuthDashboardInvestigationsInvestigationIdTypeIdRoute:
      AuthDashboardInvestigationsInvestigationIdTypeIdRoute
  }

const AuthDashboardInvestigationsInvestigationIdRouteWithChildren =
  AuthDashboardInvestigationsInvestigationIdRoute._addFileChildren(
    AuthDashboardInvestigationsInvestigationIdRouteChildren
  )

interface AuthDashboardRouteChildren {
  AuthDashboardProfileRoute: typeof AuthDashboardProfileRoute
  AuthDashboardToolsRoute: typeof AuthDashboardToolsRoute
  AuthDashboardVaultRoute: typeof AuthDashboardVaultRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardCustomTypesTypeIdRoute: typeof AuthDashboardCustomTypesTypeIdRoute
  AuthDashboardEnrichersEnricherIdRoute: typeof AuthDashboardEnrichersEnricherIdRoute
  AuthDashboardEnrichersNewRoute: typeof AuthDashboardEnrichersNewRoute
  AuthDashboardFlowsFlowIdRoute: typeof AuthDashboardFlowsFlowIdRoute
  AuthDashboardInvestigationsInvestigationIdRoute: typeof AuthDashboardInvestigationsInvestigationIdRouteWithChildren
  AuthDashboardCustomTypesIndexRoute: typeof AuthDashboardCustomTypesIndexRoute
  AuthDashboardEnrichersIndexRoute: typeof AuthDashboardEnrichersIndexRoute
  AuthDashboardFlowsIndexRoute: typeof AuthDashboardFlowsIndexRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardProfileRoute: AuthDashboardProfileRoute,
  AuthDashboardToolsRoute: AuthDashboardToolsRoute,
  AuthDashboardVaultRoute: AuthDashboardVaultRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardCustomTypesTypeIdRoute: AuthDashboardCustomTypesTypeIdRoute,
  AuthDashboardEnrichersEnricherIdRoute: AuthDashboardEnrichersEnricherIdRoute,
  AuthDashboardEnrichersNewRoute: AuthDashboardEnrichersNewRoute,
  AuthDashboardFlowsFlowIdRoute: AuthDashboardFlowsFlowIdRoute,
  AuthDashboardInvestigationsInvestigationIdRoute:
    AuthDashboardInvestigationsInvestigationIdRouteWithChildren,
  AuthDashboardCustomTypesIndexRoute: AuthDashboardCustomTypesIndexRoute,
  AuthDashboardEnrichersIndexRoute: AuthDashboardEnrichersIndexRoute,
  AuthDashboardFlowsIndexRoute: AuthDashboardFlowsIndexRoute
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRouteWithChildren
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  MiddlewareRoute: MiddlewareRoute,
  RegisterRoute: RegisterRoute
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
